# Generated by Django 3.1.5 on 2021-04-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='img',
            field=models.FileField(upload_to='pic'),
        ),
    ]
